app-id: org.example.test
runtime: org.freedesktop.Platform
runtime-version: '24.08beta'
sdk: org.freedesktop.Sdk
command: test
add-extensions:
  org.freedesktop.Sdk.Extension.rust-nightly:
    version: '24.08beta'
    directory: sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.rust-nightly
modules:
  - name: test
    buildsystem: simple
    build-commands:
      - mkdir -p ${FLATPAK_DEST}/sdk
      - install -Dm 0755 test.sh ${FLATPAK_DEST}/bin/test
    sources:
      - type: script
        dest-filename: test.sh
        commands:
          - set -eu
          - export PATH=$PATH:/app/sdk/extra/sdk/rust-nightly/bin
          - |
            for i in $(cd /app/sdk/extra/sdk/rust-nightly/bin && find * -maxdepth 1 -type f|grep -Ev "cargo-miri|rust-demangler|rls|rust-gdbgui|rust-lldb"); do
              echo "Launching ${i}"
              "${i}" "--version"
            done
