name: Smoketests

on:
  push:
    branches:
      - 'master'
      - 'beta'
      - 'branch/**'
      - 'create-pull-request/**'
  pull_request:

jobs:
  smoketests:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install latest flatpak
      run: |
        sudo add-apt-repository ppa:flatpak/stable
        sudo apt-get update
        sudo apt-get install -y flatpak

    - name: Set up flathub remote
      run: |
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

    - name: Install org.flatpak.Builder
      run: |
        flatpak install --user -y flathub org.flatpak.Builder

    - name: Build org.freedesktop.Sdk.Extension.rust-nightly
      run: |
        mkdir -p org.freedesktop.Sdk.Extension.rust-nightly && cd org.freedesktop.Sdk.Extension.rust-nightly
        dbus-run-session flatpak run org.flatpak.Builder --verbose --user --sandbox --force-clean --repo=repo \
          --install-deps-from=flathub-beta --ccache builddir ../org.freedesktop.Sdk.Extension.rust-nightly.yml
        cd repo && dbus-run-session flatpak remote-add --user --no-gpg-verify rust-nightly file://$(pwd)
        dbus-run-session flatpak install --user -y rust-nightly org.freedesktop.Sdk.Extension.rust-nightly

    - name: Build and install the test manifest
      run: |
        mkdir -p org.example.test && cd org.example.test
        dbus-run-session flatpak run org.flatpak.Builder --verbose --user --force-clean --repo=repo \
          --install-deps-from=flathub-beta --default-branch=localtest --ccache --install \
          builddir ../.github/org.example.test.yaml

    - name: Run the test
      run: flatpak run --devel org.example.test//localtest
