name: Check for updates
on:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch: {}
jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'flathub'
    strategy:
      matrix:
        branch: [ branch/23.08, branch/24.08 ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        with:
          args: --update --edit-only org.freedesktop.Sdk.Extension.rust-nightly.yml

      - name: Install dependencies
        run: |
          sudo apt install -y pip git
          pip install --user toml==0.10.2 ruamel.yaml==0.18.6

      - name: Update rust nightly
        run: |
          python .github/scripts/update.py
          git restore org.freedesktop.Sdk.Extension.rust-nightly.appdata.xml || true

      - name: Create pull request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch-suffix: "random"
          commit-message: Update rust-nightly modules
          title: "Update rust-nightly modules"
          body: Update rust-nightly modules
          delete-branch: true
          sign-commits: true
