name: Check for updates
on:
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch: {}
jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'flathub'
    strategy:
      matrix:
        branch: [ branch/23.08, branch/24.08 ]
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ matrix.branch }}

      - uses: docker://ghcr.io/flathub-infra/flatpak-external-data-checker:latest@sha256:9e64f59dc8b92b4e7cf325a3f2ef98a64beaf721b58803801d3bf66269203221
        with:
          args: --update --edit-only org.freedesktop.Sdk.Extension.rust-nightly.yml

      - name: Install dependencies
        run: |
          sudo apt install -y pip git
          pip install --user toml==0.10.2 ruamel.yaml==0.18.6

      - name: Update rust nightly
        run: |
          python .github/scripts/update.py
          git restore org.freedesktop.Sdk.Extension.rust-nightly.appdata.xml || true

      - name: Create pull request
        if: ${{ success() }}
        id: create-pr
        # 7.0.8
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          branch-suffix: "random"
          commit-message: Update rust-nightly modules
          title: "Update rust-nightly modules"
          body: Update rust-nightly modules
          delete-branch: true
          sign-commits: true
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Pause for a while
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: sleep 2000

      - name: Set auto-merge
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: gh pr merge --merge --auto ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
